import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const source = resolve(here, "../../server/src/data/monopoly_board_game.json");
const target = resolve(here, "../programs/robinverse/src/board.rs");

const data = JSON.parse(readFileSync(source, "utf8"));

const GROUP_NUMBERS = {
  transport: 1,
  utility: 2,
  india: 3,
  china: 4,
  brazil: 5,
  russia: 6,
  germany: 7,
  australia: 8,
  uk: 9,
  usa: 10,
};

const TILE_KINDS = {
  go: "Go",
  property: "Property",
  transport: "Transport",
  utility: "Utility",
  tax: "Tax",
  fortune: "Fortune",
  treasury: "Treasury",
  jail: "Jail",
  free_parking: "FreeParking",
  go_to_jail: "GoToJail",
};

function kindOf(tile) {
  const kind = TILE_KINDS[tile.type];
  if (!kind) throw new Error(`unmapped tile type "${tile.type}" at id ${tile.id}`);
  return kind;
}

function rentsOf(tile) {
  const rent = tile.rent ?? {};
  if (tile.type === "property") {
    return [
      rent.base ?? 0,
      rent.monopoly ?? 0,
      rent.house_1 ?? 0,
      rent.house_2 ?? 0,
      rent.house_3 ?? 0,
      rent.house_4 ?? 0,
      rent.hotel ?? 0,
    ];
  }
  if (tile.type === "transport") {
    return [
      rent.owned_1 ?? 0,
      rent.owned_2 ?? 0,
      rent.owned_3 ?? 0,
      rent.owned_4 ?? 0,
      0,
      0,
      0,
    ];
  }
  if (tile.type === "utility") {
    return [
      rent.owned_1_multiplier ?? 4,
      rent.owned_2_multiplier ?? 10,
      0,
      0,
      0,
      0,
      0,
    ];
  }
  return [0, 0, 0, 0, 0, 0, 0];
}

const groupMembers = new Map();
for (const tile of data.board) {
  const group = GROUP_NUMBERS[tile.group] ?? 0;
  if (!group) continue;
  if (!groupMembers.has(group)) groupMembers.set(group, []);
  groupMembers.get(group).push(tile.id);
}

const tiles = data.board.map((tile) => {
  const group = GROUP_NUMBERS[tile.group] ?? 0;
  const members = groupMembers.get(group) ?? [];
  const padded = [...members, ...Array(4 - members.length).fill(255)].slice(0, 4);
  return {
    index: tile.id,
    name: tile.name,
    kind: kindOf(tile),
    group,
    price: tile.price ?? 0,
    mortgageValue: tile.mortgage_value ?? 0,
    houseCost: tile.house_cost ?? 0,
    hotelCost: tile.hotel_cost ?? 0,
    taxAmount: tile.amount ?? 0,
    rents: rentsOf(tile),
    groupMembers: padded,
    groupSize: members.length,
  };
});

if (tiles.length !== 40) throw new Error(`expected 40 tiles, got ${tiles.length}`);

const rustTiles = tiles
  .map(
    (tile) => `    Tile {
        index: ${tile.index},
        name: ${JSON.stringify(tile.name)},
        kind: TileKind::${tile.kind},
        group: ${tile.group},
        price: ${tile.price},
        mortgage_value: ${tile.mortgageValue},
        house_cost: ${tile.houseCost},
        hotel_cost: ${tile.hotelCost},
        tax_amount: ${tile.taxAmount},
        rents: [${tile.rents.join(", ")}],
        group_members: [${tile.groupMembers.join(", ")}],
        group_size: ${tile.groupSize},
    },`,
  )
  .join("\n");

const cardList = (cards) =>
  cards.map((text) => `    ${JSON.stringify(text)},`).join("\n");

const out = `// @generated by onchain/scripts/gen-board.mjs — do not edit by hand.
// Source: server/src/data/monopoly_board_game.json
// Regenerate with: node onchain/scripts/gen-board.mjs

use anchor_lang::prelude::*;

#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy, PartialEq, Eq, Debug)]
pub enum TileKind {
    Go,
    Property,
    Transport,
    Utility,
    Tax,
    Fortune,
    Treasury,
    Jail,
    FreeParking,
    GoToJail,
}

pub struct Tile {
    pub index: u8,
    pub name: &'static str,
    pub kind: TileKind,
    pub group: u8,
    pub price: u32,
    pub mortgage_value: u32,
    pub house_cost: u32,
    pub hotel_cost: u32,
    pub tax_amount: u32,
    /// Property: [base, monopoly, house1..house4, hotel].
    /// Transport: [owned1..owned4, 0, 0, 0].
    /// Utility: [multiplier_1, multiplier_2, 0, 0, 0, 0, 0].
    pub rents: [u32; 7],
    /// Tile indices sharing this colour group, padded with 255.
    pub group_members: [u8; 4],
    pub group_size: u8,
}

impl Tile {
    pub fn is_ownable(&self) -> bool {
        matches!(
            self.kind,
            TileKind::Property | TileKind::Transport | TileKind::Utility
        )
    }

    pub fn members(&self) -> impl Iterator<Item = usize> + '_ {
        self.group_members
            .iter()
            .filter(|index| **index != 255)
            .map(|index| *index as usize)
    }
}

pub const BOARD_SIZE: usize = 40;
pub const GO_SALARY: u32 = ${data.meta?.go_salary ?? 200};
pub const JAIL_INDEX: u8 = 10;
pub const GO_TO_JAIL_INDEX: u8 = 30;
pub const JAIL_FINE: u32 = 50;
pub const TOTAL_HOUSES: u8 = ${data.building_rules.total_houses_available};
pub const TOTAL_HOTELS: u8 = ${data.building_rules.total_hotels_available};

pub const BOARD: [Tile; BOARD_SIZE] = [
${rustTiles}
];

pub const FORTUNE_CARDS: [&str; ${data.fortune_cards.length}] = [
${cardList(data.fortune_cards)}
];

pub const TREASURY_CARDS: [&str; ${data.treasury_cards.length}] = [
${cardList(data.treasury_cards)}
];

pub fn tile(index: u8) -> &'static Tile {
    &BOARD[index as usize % BOARD_SIZE]
}
`;

writeFileSync(target, out);
console.log(
  `wrote ${target}\n  ${tiles.length} tiles, ${data.fortune_cards.length} fortune, ${data.treasury_cards.length} treasury`,
);
